# Toml
[[plugins]]
repo  = 'cespare/vim-toml'
on_ft = ['toml']

# Markdown
[[plugins]]
repo = 'plasticboy/vim-markdown'
on_ft = ['markdown']


[[plugins]]
repo   = 'Shougo/unite.vim'

[[plugins]]
repo = 'Shougo/neosnippet.vim'
on_event = 'InsertCharPre'
on_ft = 'snippet'
depends = 'context_filetype.vim'
hook_source = '''
source ~/.config/nvim/plugins/neosnippet.rc.vim
'''

[[plugins]]
repo = 'Shougo/deoplete.nvim'
depends = 'context_filetype.vim'
on_event = 'InsertEnter'
hook_source = '''
source ~/.config/nvim/plugins/deoplete.rc.vim
'''
