#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='nvim'
export VISUAL='nvim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

export SYSTEMC_HOME=/usr/local/include/SystemC/systemc-2.3.3
export CPLUS_INCLUDE_PATH=$SYSTEMC_HOME/include
export LIBRARY_PATH=$SYSTEMC_HOME/lib-macosx64
export PATH=$PATH:/usr/local/bin
export PATH=$PATH:/Users/raven/Library/Python/3.7/bin/

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path
#set the Golang Path
export GOROOT=/usr/local/opt/go/libexec 
export GOPATH=$HOME/Development/Software
export PATH=$PATH:$GOROOT/bin:$GOPATH/bin
# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Set the list of directories that Zsh searches for programs.
path=(
  /usr/local/{bin,sbin}
  $path
)

#
# Less
#

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Setting PATH for Python 3.7
# The original version is saved in .zprofile.pysave
export PKG_CONFIG_PATH="/usr/local/lib/pkgconfig/"
PATH="/Library/Frameworks/Python.framework/Versions/3.7/bin:${PATH}"
export PATH
